FROM ubuntu:20.10

RUN apt-get update && yes | apt-get upgrade

RUN apt-get install -y git python3 python3-pip sudo

RUN useradd -m dadman

RUN chown -R dadman:dadman /home/dadman/

COPY --chown=dadman . /home/dadman/app/

USER dadman
 
RUN pip install -U pip

RUN pip install jupyter

RUN cd /home/dadman/app/ pip3 install -r requirements.txt

WORKDIR /home/dadman/app

RUN jupyter notebook --generate-config --allow-root
RUN echo "c.NotebookApp.password = u'sha1:6a3f528eec40:6e896b6e4828f525a6e20e5411cd1c8075d68619'" >> /root/.jupyter/jupyter_notebook_config.pyEXPOSE 8888CMD ["jupyter", "notebook", "--allow-root", "--notebook-dir=/tensorflow/models/research/object_detection", "--ip=0.0.0.0", "--port=8888", "--no-browser"]